/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantaescritorio;

/**
 *
 * @author tduarte
 */
public class telaPlantaEscritorio extends javax.swing.JFrame {

    /**
     * Creates new form telaPlantaEscritorio
     */
    public telaPlantaEscritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Lugar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel_FundoPlanta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton_Lugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/computador_vazio.png"))); // NOI18N
        jButton_Lugar1.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton_Lugar1.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton_Lugar1.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton_Lugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Lugar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Lugar1);
        jButton_Lugar1.setBounds(290, 80, 40, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/computador_amarelo.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 190, 40, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/computador_verde.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 90, 40, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/computador_vermelho.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 180, 40, 30);

        jLabel_FundoPlanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/planta_fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel_FundoPlanta);
        jLabel_FundoPlanta.setBounds(0, 0, 530, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Lugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Lugar1ActionPerformed
        // TODO add your handling code here:
        MenuUsuario edit = new MenuUsuario();
        edit.setVisible(true);
        // jButton_Lugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/computador_emuso.png")));
    }//GEN-LAST:event_jButton_Lugar1ActionPerformed

    public void usar(){
        jButton_Lugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/computador_emuso.png")));
    }
    

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MenuUsuario edit = new MenuUsuario();
        edit.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MenuUsuario edit = new MenuUsuario();
        edit.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MenuUsuario edit = new MenuUsuario();
        edit.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPlantaEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPlantaEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPlantaEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPlantaEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                telaPlantaEscritorio frame = new telaPlantaEscritorio();
                frame.setSize(500,300);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_Lugar1;
    private javax.swing.JLabel jLabel_FundoPlanta;
    // End of variables declaration//GEN-END:variables
}
